### ISSUE TITLE
Ros, iai_kinect2 issues

### ISSUE THREAD

**Issue by ipekbocegi** [Parth-Mehrotra/Tools#1]
Hi there,
I see your post 
http://robotics.stackexchange.com/questions/6632/ros-iai-kinect2-issues
I have exactly the same problems with you. Have you find a solution??  If you don't mind I have a few question:

* What is your graphic card Intel or Nvidia? I mean when you go additional drivers which one is selected Xorg thing or any Nvidia like 331, 340, 346, 349 etc?
* Did you changed anything in "etc/default/grub" like "quite splash" to "quite splash nomodeset"?
* Did you modified blacklist.conf" file?
* Did you try Blumlebee or Beignet things?
* Have you faced with any black screen on reboot?
* Do you have OpenCL now?
* Did you lost some random characters on screen due to low graphic speed?

Those are my experiences. I am working with Asus X555LN, intel core i5, Nvidia Geforce 840M, Ubuntu 14.04, Ros indigo, Kinect2 camera. I used to work with Kinect2 but last month something happened I guess during an update or upgrade and then my computer gave me black screen on regular start. I have been dealing with building Ubuntu, installing graphic driver and reinstalling everything. 

I think main problem is about Nvidia. It blocks OpenCL, so libfreenect2, so iaiKinect2

If you found a solution please contact me via this issue

Kind regards

**Comment by Parth-Mehrotra** [comment]
Hi, I never say this issue, sorry.

But to answer your question. I have an intel i7, integrated graphics card, although I have tried it on nvidia.  I haven't changed any of those files. I have not tried tried Blumlebee or Beignet. I have not faced any black screens on reboot. I believe OpenCL is packaged with ROS, so I think so, if not, I have not explicitly installed that. I do not have random charactors on the screen.

I have a Toshiba Satalite p7555, i7, 6gb ram.

Have you had any luch with this issue yet?

**Comment by ipekbocegi** [comment]
I give up the issue thanks
